permalink: /:year/:month/:title

server: true
server_port: 4000
auto: true

markdown: rdiscount

pygments: true

rdiscount:
  extensions: [autolink]

source: ./site
plugins: ./site/_plugins
destination: ./web

asset_path : assets

title: Built In Bruges
author:
  name: Bert Devriese
  email: hello@builtinbruges.com
  github: builtinbruges
  twitter: builtinbruges
  dribbble: builtinbruges

typekit:
  kit_id: kxh3qqe

sass:
  syntax: scss
  style: compressed

analytics:
  tracker_id: UA-40297203-1
  tracker_domain: builtinbruges.com

exclude: [README.md]