permalink: /:year/:month/:title
post_dirs: true
url: http://www.builtinbruges.com

markdown: redcarpet
highlighter: true

timezone: Europe/Brussels
encoding: UTF-8

name: Built In Bruges
author:
  name: Bert Devriese
  email: bert@builtinbruges.com
  github: brtdv
  twitter: brtdv
  dribbble: brtdv

typekit:
  kit_id: kxh3qqe

sass:
  syntax: sass
  style: compressed

analytics:
  tracker_id: UA-40297203-1
  tracker_domain: builtinbruges.com

exclude: [README.md, Gemfile, Gemfile.lock]