permalink: /:year/:month/:title
post_dirs: true
url: http://www.builtinbruges.com

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - autolink

timezone: Europe/Brussels
encoding: UTF-8

title: Built In Bruges
description: "Built in Bruges delivers high quality web/app design & development for businesses and startups"
author:
  name: Bert Devriese
  email: bert@builtinbruges.com
  github: brtdv
  twitter: brtdv
  dribbble: brtdv

typekit:
  kit_id: kxh3qqe

sass:
  style: :compressed

analytics:
  tracker_id: UA-40297203-1
  tracker_domain: builtinbruges.com

exclude: [README.md, Gemfile, Gemfile.lock, publish.sh]