permalink: /:year/:month/:title

full_url: http://www.builtinbruges.com

port: 4000

markdown: redcarpet

pygments: true

rdiscount:
  extensions: [autolink]

redcarpet:
  extensions: [autolink]

paginate_file: blog.html
paginate_path: "blog/page:num"
paginate: 10

source: ./site
plugins: ./site/_plugins
destination: ./web

asset_path : assets

title: Built In Bruges
author:
  name: Bert Devriese
  email: hello@builtinbruges.com
  github: builtinbruges
  twitter: builtinbruges
  dribbble: builtinbruges

typekit:
  kit_id: kxh3qqe

sass:
  syntax: scss
  style: compressed

analytics:
  tracker_id: UA-40297203-1
  tracker_domain: builtinbruges.com

exclude: [README.md]